-- Creates the events table for Connections puzzle solves (Weekly, Custom, and
-- eventually Featured — see puzzle_type below), matching the existing pattern
-- of solve_events / sandwich_events / bb_solve_events: one row per completed
-- game, anon-insert-only, used to power a future stats view the same way
-- fetchDailyStats/fetchGlobalStats already do for the other game modes.
--
-- Archive puzzles are intentionally NOT logged here — they're untracked/for-fun,
-- same as they already are for local stats.
--
-- NOTE: if this table already exists (created before used_hint/puzzle_type/
-- custom_code existed), `create table if not exists` below is a no-op and
-- those columns will NOT be added — run connections_events_missing_columns.sql
-- instead to catch an existing table up to this shape.
--
-- Run this in the Supabase SQL Editor.

create table if not exists connections_events (
  id bigint generated by default as identity primary key,
  week_num integer not null, -- 0 for non-main puzzles, which have no week number
  won boolean not null,
  mistakes integer not null,
  solve_order jsonb not null, -- e.g. [2,1,4,3] — difficulty of each group in the order it was solved
  used_hint boolean not null default false, -- true if the "reveal category" hint was used at all this game
  puzzle_type text not null default 'main' check (puzzle_type in ('main', 'custom', 'featured')),
  custom_code text, -- links to custom_connections_puzzles.code for 'custom'/'featured' rows; null for 'main'
  timestamp text not null,
  created_at timestamptz not null default now()
);

alter table connections_events enable row level security;

create policy "Allow anon insert" on connections_events
  for insert to anon with check (true);

-- Verify with (should return 201, not 401/42501):
-- insert into connections_events (week_num, won, mistakes, solve_order, used_hint, puzzle_type, custom_code, timestamp)
-- values (0, true, 1, '[1,2,3,4]'::jsonb, false, 'custom', 'testcode', now()::text)
-- returning *;
-- Then delete the test row: delete from connections_events where week_num = 0;
