-- Creates the events table for the main (Weekly) Connections puzzle, matching
-- the existing pattern of solve_events / sandwich_events / bb_solve_events:
-- one row per completed Weekly game, anon-insert-only, used to power a future
-- stats view the same way fetchDailyStats/fetchGlobalStats already do for
-- the other game modes.
--
-- Archive and Custom puzzles are intentionally NOT logged here — they're
-- untracked/for-fun, same as they already are for local stats.
--
-- Run this in the Supabase SQL Editor.

create table if not exists connections_events (
  id bigint generated by default as identity primary key,
  week_num integer not null,
  won boolean not null,
  mistakes integer not null,
  solve_order jsonb not null, -- e.g. [2,1,4,3] — difficulty of each group in the order it was solved
  timestamp text not null,
  created_at timestamptz not null default now()
);

alter table connections_events enable row level security;

create policy "Allow anon insert" on connections_events
  for insert to anon with check (true);

-- Verify with (should return 201, not 401/42501):
-- insert into connections_events (week_num, won, mistakes, solve_order, timestamp)
-- values (0, true, 1, '[1,2,3,4]'::jsonb, now()::text)
-- returning *;
-- Then delete the test row: delete from connections_events where week_num = 0;
